<?php
namespace App\Services;use App\Core\Database;
class ExternalAuthService{
 public static function canonicalPayload(array$p):string{return implode("\n",[(string)($p['uid']??''),(string)($p['sales_id']??''),(string)($p['name']??''),(string)($p['role']??''),(string)($p['ts']??''),(string)($p['nonce']??'')]);}
 public function accept(array$p):array{global$config;$secret=(string)$config['auth']['handoff_secret'];if(strlen($secret)<32)throw new \RuntimeException('AUTH_HANDOFF_SECRET is not configured.');
  $uid=trim((string)($p['uid']??''));$sales=trim((string)($p['sales_id']??''));$name=trim((string)($p['name']??''));$role=trim((string)($p['role']??''));$ts=(int)($p['ts']??0);$nonce=trim((string)($p['nonce']??''));$sig=strtolower(trim((string)($p['sig']??'')));
  if($uid===''||$name===''||$nonce===''||$ts<=0||$sig==='')throw new \RuntimeException('Incomplete authentication handoff.');if(!in_array($role,['admin','sales'],true))throw new \RuntimeException('Invalid role.');if($role==='sales'&&($sales===''||!ctype_digit($sales)))throw new \RuntimeException('Sales handoff requires numeric sales_id.');if(abs(time()-$ts)>max(30,(int)$config['auth']['handoff_max_age_seconds']))throw new \RuntimeException('Authentication handoff expired.');if(!preg_match('/^[A-Za-z0-9._:-]{8,128}$/',$nonce))throw new \RuntimeException('Invalid nonce.');
  $expected=hash_hmac('sha256',self::canonicalPayload(['uid'=>$uid,'sales_id'=>$sales,'name'=>$name,'role'=>$role,'ts'=>$ts,'nonce'=>$nonce]),$secret);if(!hash_equals($expected,$sig))throw new \RuntimeException('Authentication signature is invalid.');
  $pdo=Database::connection();$pdo->beginTransaction();try{$h=$pdo->prepare("INSERT INTO auth_handoffs(nonce,external_user_id,sales_id,display_name,role,source_ip,payload_json,accepted_at) VALUES(?,?,?,?,?,?,?,NOW())");$h->execute([$nonce,$uid,$role==='sales'?(int)$sales:null,$name,$role,substr((string)($_SERVER['REMOTE_ADDR']??''),0,45),json_encode(['uid'=>$uid,'sales_id'=>$sales,'name'=>$name,'role'=>$role,'ts'=>$ts,'nonce'=>$nonce],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);
   $username=$role==='sales'?$sales:'ext_'.preg_replace('/[^A-Za-z0-9._-]+/','_',$uid);
   $u=$pdo->prepare("INSERT INTO users(sales_id,external_user_id,username,password_hash,display_name,role,active,auth_source,last_handoff_at,created_at,updated_at) VALUES(?,?,?,NULL,?,?,1,'coolerdepot',NOW(),NOW(),NOW()) ON DUPLICATE KEY UPDATE sales_id=VALUES(sales_id),external_user_id=VALUES(external_user_id),display_name=VALUES(display_name),role=VALUES(role),active=1,auth_source='coolerdepot',last_handoff_at=NOW(),updated_at=NOW()");$u->execute([$role==='sales'?(int)$sales:null,$uid,$username,$name,$role]);
   $f=$pdo->prepare("SELECT id,sales_id,external_user_id,username,display_name,role,active,auth_source FROM users WHERE external_user_id=? LIMIT 1");$f->execute([$uid]);$user=$f->fetch();if(!$user)throw new \RuntimeException('Could not create or resolve user.');$x=$pdo->prepare("UPDATE auth_handoffs SET user_id=? WHERE nonce=?");$x->execute([(int)$user['id'],$nonce]);$pdo->commit();return$user;
  }catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();if(stripos($e->getMessage(),'Duplicate')!==false)throw new \RuntimeException('Authentication handoff was already used.');throw$e;}
 }
}
